services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: andiajazi
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: on-failure

networks:
  db:
    driver: bridge

volumes:
  db: